blank_issues_enabled: false
contact_links:
  - name: 🔗 CurseForge Page
    url: https://www.curseforge.com/minecraft/mc-mods/singleplayer-exe
    about: Check the main mod page for updates and information
