blank_issues_enabled: false

contact_links:
  - name: 🔗 My CurseForge Projects
    url: https://www.curseforge.com/members/politas180/projects
    about: Check out all my Minecraft mods, updates, and downloads
